# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:

- script: hostname
  displayName: Show Hostname

- script: whoami
  displayName: Show User

- script: |
    hostname
    whoami
    echo %COMPUTERNAME%
  displayName: System Info

- script: |
    dir C:\Users
  displayName: List Users

- task: AzureCLI@3
  inputs:
    connectionType: 'azureRM'
    azureSubscription: 'Azure subscription 1(b7ce91a3-5078-4af1-93ad-6c9d2218a4b1)'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: 'az account show'