trigger:
- main

pool:
  name: Default

steps:

- template: templates/terraform-install.yml
  parameters:
    terraformVersion: 1.14.4

- template: templates/terraform-validate.yml
  parameters:
    workingDirectory: terraform