trigger: none

pool:
  name: Default

parameters:
- name: environment
  type: string
  default: prod

variables:
  myEnvironment: dev

steps:

- script: |
    echo Parameter = ${{ parameters.environment }}
    echo Variable  = $(myEnvironment)

