trigger:
- main

pool:
  name: Default

stages:

- stage: Validate
  displayName: Terraform Validate
  jobs:
  - job: Validate
    steps:
    - script: |
        terraform version
        cd terraform
        terraform init
        terraform validate
      displayName: Terraform Init and Validate

- stage: Plan
  displayName: Terraform Plan
  dependsOn: Validate
  jobs:
  - job: Plan
    steps:
    - task: AzureCLI@2
      displayName: Terraform Plan
      inputs:
        azureSubscription: 'sc-azure-platform-lab'
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          terraform version
          cd terraform
          terraform init
          terraform plan -var="resource_group_name=rg-devops-lab" -var="location=westeurope"

- stage: Apply
  displayName: Terraform Apply
  dependsOn: Plan

  jobs:
  - job: Apply

    steps:
    - task: AzureCLI@2
      displayName: Terraform Apply

      inputs:
        azureSubscription: 'sc-azure-platform-lab'
        scriptType: ps
        scriptLocation: inlineScript

        inlineScript: |
          terraform version

          cd terraform

          terraform init

          terraform apply -auto-approve `
            -var="resource_group_name=rg-devops-lab" `
            -var="location=westeurope"