trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:

- stage: Validate
  displayName: Terraform Validate

  jobs:
  - job: Validate

    steps:

   - script: |
    wget https://releases.hashicorp.com/terraform/1.13.0/terraform_1.13.0_linux_amd64.zip
    unzip terraform_1.13.0_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
    terraform version
  displayName: Install Terraform
      

    - script: |
        cd terraform
        terraform init
        terraform validate
      displayName: Terraform Init and Validate

- stage: Plan
  displayName: Terraform Plan

  dependsOn: Validate

  jobs:
  - job: Plan

    steps:

    - script: |
    wget https://releases.hashicorp.com/terraform/1.13.0/terraform_1.13.0_linux_amd64.zip
    unzip terraform_1.13.0_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
    terraform version
  displayName: Install Terraform

    - script: |
        cd terraform
        terraform init
        terraform plan \
          -var="resource_group_name=rg-devops-lab" \
          -var="location=westeurope"
      displayName: Terraform Plan