trigger:
- none

pool:
  name: default

steps:
- script: |
    echo %PATH%
  displayName: Show PATH
- script: |
    dir "C:\tools\terraform"
  displayName: Find Terraform
- script: |
    "C:\tools\terraform\terraform.exe" version
  displayName: Terraform Full Path
- script: terraform version
  displayName: Terraform Version