parameters:
- name: workingDirectory
  type: string
  default: terraform

- name: azureSubscription
  type: string
  default: sc-azure-platform-lab

jobs:
- job: TerraformPlan
  displayName: Terraform Plan

  steps:
  - task: AzureCLI@2
    displayName: Azure Login + Terraform Init/Plan
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      scriptType: ps
      scriptLocation: inlineScript
      workingDirectory: ${{ parameters.workingDirectory }}
      inlineScript: |
        az account show
        terraform init
        terraform plan