parameters:
- name: workingDirectory
  type: string
  default: terraform

- name: sc-azure-platform-lab
  type: string

jobs:
- job: TerraformPlan
  displayName: Terraform Plan
  steps:
  - task: AzureCLI@2
    displayName: Terraform Init and Plan
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      scriptType: ps
      scriptLocation: inlineScript
      workingDirectory: ${{ parameters.workingDirectory }}
      inlineScript: |
        terraform init
        terraform plan